const $=id=>document.getElementById(id);
const palette=[{name:'Muy bajo',label:'0–<12,5',color:'#285784'},{name:'Bajo',label:'12,5–<37,5',color:'#49a9a7'},{name:'Medio',label:'37,5–<75',color:'#d4aa3d'},{name:'Alto',label:'75–100',color:'#e96c57'}];
const layerFiles={manzana:['manzanas/NORPONIENTE.geojson','manzanas/SURPONIENTE.geojson','manzanas/NORORIENTE.geojson','manzanas/CENTRO_ORIENTE.geojson','manzanas/CENTRO_PONIENTE.geojson','manzanas/SURORIENTE.geojson'],barrio:['barrios.geojson'],territorio:['territorios.geojson'],comuna:['comuna.geojson']};
const levelFields={manzana:'COD_MZN',barrio:'BARRIO',territorio:'TERRITORIO',comuna:'COMUNA'};
const barrioTerritorio={
'SAN VICENTE':'SURPONIENTE','SAN EUGENIO':'SURPONIENTE','RONDIZZONI':'SURPONIENTE','YUNGAY':'NORPONIENTE','MEIGGS':'CENTRO PONIENTE','CLUB HIPICO':'SURPONIENTE','REPUBLICA':'CENTRO PONIENTE','EJERCITO':'CENTRO PONIENTE','BRASIL':'NORPONIENTE','MATTA NORTE':'CENTRO ORIENTE','BALMACEDA':'NORPONIENTE','PANAMA':'NORPONIENTE','DIEZ DE JULIO':'CENTRO ORIENTE','SANTA ISABEL':'CENTRO ORIENTE','SAN BORJA':'CENTRO ORIENTE','PARQUE ALMAGRO':'CENTRO ORIENTE','HUEMUL':'SURORIENTE','FRANKLIN':'SURORIENTE','SIERRA BELLA':'SURORIENTE','VIEL':'SURORIENTE','MATTA SUR':'SURORIENTE','BOGOTA':'SURORIENTE','SANTA ELENA':'SURORIENTE','SANTA ANA':'NORORIENTE','SANTA LUCIA FORESTAL':'NORORIENTE','CENTRO HISTORICO':'NORORIENTE',"PARQUE O'HIGGINS":'SURPONIENTE'};
const territorioBarrio=name=>barrioTerritorio[norm(name)]||null;
const territorioDePropiedades=p=>{const propio=String(p?.TERRITORIO??'').trim();return propio&&!['-','–','—','SIN DATO','S/D','NULL'].includes(norm(propio))?propio:territorioBarrio(p?.BARRIO)};
const inverseCodes=new Set(['IAT_1','IAT_7','IUT_3','IUT_7']);
const strategicLinks={
  IAT_1:{dimension:'AMBIENTAL',eje:'GESTIÓN INTEGRAL DE RESIDUOS',componentes:['ASEO Y LIMPIEZA URBANA']},
  IAT_2:{dimension:'AMBIENTAL',eje:'GESTIÓN INTEGRAL DE RESIDUOS',componentes:['ASEO Y LIMPIEZA URBANA','MEDIOAMBIENTE']},
  IAT_3:{dimension:'AMBIENTAL',eje:'INFRAESTRUCTURA VERDE URBANA',componentes:['ÁREAS VERDES']},
  IAT_4:{dimension:'AMBIENTAL',eje:'INFRAESTRUCTURA VERDE URBANA',componentes:['ÁREAS VERDES']},
  IAT_5:{dimension:'AMBIENTAL',eje:'INFRAESTRUCTURA VERDE URBANA',componentes:['ÁREAS VERDES','MEDIOAMBIENTE']},
  IAT_6:{dimension:'AMBIENTAL',eje:'AMBIENTE SALUDABLE',componentes:['ASEO Y LIMPIEZA URBANA','SERVICIOS','SOCIAL']},
  IAT_7:{dimension:'AMBIENTAL',eje:'AMBIENTE SALUDABLE',componentes:['MEDIOAMBIENTE']},
  IAT_8:{dimension:'AMBIENTAL',eje:'INFRAESTRUCTURA VERDE URBANA',componentes:['ÁREAS VERDES']},
  IAT_9:{dimension:'AMBIENTAL',eje:'INFRAESTRUCTURA VERDE URBANA',componentes:['ÁREAS VERDES','MEDIOAMBIENTE']},
  IUT_1:{dimension:'URBANA',eje:'ESPACIOS PÚBLICOS',componentes:['ESPACIO PÚBLICO INTEGRAL','ESPACIO PÚBLICO']},
  IUT_2:{dimension:'URBANA',eje:'REVITALIZACIÓN PATRIMONIAL',componentes:['CULTURA','ESPACIO PÚBLICO INTEGRAL']},
  IUT_3:{dimension:'URBANA',eje:'MOVILIDADES JUSTAS',componentes:['TRANSITO / MOVILIDAD','ESPACIO PÚBLICO INTEGRAL']},
  IUT_4:{dimension:'URBANA',eje:'REVITALIZACIÓN PATRIMONIAL',componentes:['CULTURA','ESPACIO PÚBLICO INTEGRAL']},
  IUT_5:{dimension:'URBANA',eje:'MOVILIDADES JUSTAS',componentes:['TRANSITO / MOVILIDAD']},
  IUT_6:{dimension:'URBANA',eje:'REVITALIZACIÓN PATRIMONIAL',componentes:['CULTURA','TURISMO']},
  IUT_7:{dimension:'URBANA',eje:'GESTIÓN DE VIVIENDA',componentes:['VIVIENDA']},
  IUT_8:{dimension:'URBANA',eje:'REVITALIZACIÓN PATRIMONIAL',componentes:['CULTURA','ESPACIO PÚBLICO INTEGRAL']},
  IST_1:{dimension:'SOCIOCULTURAL',eje:'SEGURIDAD HUMANA',componentes:['SEGURIDAD']},
  IST_2:{dimension:'SOCIOCULTURAL',eje:'SALUD Y VIDA SANA',componentes:['SALUD']},
  IST_3:{dimension:'SOCIOCULTURAL',eje:'SALUD Y VIDA SANA',componentes:['DEPORTE','SALUD']},
  IST_4:{dimension:'SOCIOCULTURAL',eje:'SALUD Y VIDA SANA',componentes:['SALUD']},
  IST_5:{dimension:'SOCIOCULTURAL',eje:'SALUD Y VIDA SANA',componentes:['SALUD']},
  IST_6:{dimension:'SOCIOCULTURAL',eje:'CULTURA Y EDUCACIÓN',componentes:['CULTURA']},
  IST_7:{dimension:'SOCIOCULTURAL',eje:'SEGURIDAD HUMANA',componentes:['SEGURIDAD','SOCIAL']},
  IST_8:{dimension:'SOCIOCULTURAL',eje:'CULTURA Y EDUCACIÓN',componentes:['EDUCACIÓN']},
  IET_1:{dimension:'ECONÓMICA',eje:'FOMENTO DE SECTORES',componentes:['DESARROLLO ECONÓMICO LOCAL']},
  IET_2:{dimension:'ECONÓMICA',eje:'INFRAESTRUCTURA Y LOGÍSTICA',componentes:['DESARROLLO ECONÓMICO LOCAL']},
  IET_3:{dimension:'ECONÓMICA',eje:'FOMENTO DE SECTORES',componentes:['TURISMO','DESARROLLO ECONÓMICO LOCAL']},
  IET_4:{dimension:'ECONÓMICA',eje:'INNOVACIÓN Y DESARROLLO',componentes:['DESARROLLO ECONÓMICO LOCAL']}
};
const state={db:null,initiatives:[],layers:{},scale:'barrio',year:2025,compareYear:null,selectedDimensions:['IAT','IUT','IST','IET','IIT'],selectedIndicators:[],selectedFeature:null,view:'ranking'};
let map;
const norm=s=>String(s??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().replace(/[^A-Z0-9]/g,'');
const fmt=v=>Number.isFinite(v)?v.toLocaleString('es-CL',{minimumFractionDigits:2,maximumFractionDigits:2}):'–';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const indicatorByCode=code=>state.db.indicadores.find(i=>i.codigo===code);
function rangeFor(v){if(!Number.isFinite(v))return null;if(v<.125)return palette[0];if(v<.375)return palette[1];if(v<.75)return palette[2];return palette[3]}
const rowFor=(name,year)=>state.db.series.find(r=>r.anio===year&&norm(r.nombre)===norm(name));
const publishable=(code,year)=>Boolean(indicatorByCode(code)?.[`publicado_${year}`]);
const indicatorDescription=i=>i.descripcion||`Mide territorialmente ${String(i.indicador).toLowerCase()} y expresa el resultado normalizado en una escala de 0 a 1. Unidad de referencia: ${i.unidad||'no especificada'}.`;
const directionText=i=>inverseCodes.has(i.codigo)?'Normalización inversa: el valor original fue invertido; un resultado normalizado mayor representa una condición territorial más favorable.':'Resultado normalizado según el sentido definido en Síntesis 2.';
function codesAvailable(){return state.db.indicadores.filter(i=>state.selectedDimensions.some(p=>i.codigo.startsWith(p))&&(publishable(i.codigo,state.year)||(state.compareYear&&publishable(i.codigo,state.compareYear))))}
function barrioValue(name,year){const row=rowFor(name,year),vals=state.selectedIndicators.map(c=>publishable(c,year)?Number(row?.valores?.[c]):NaN).filter(Number.isFinite);return vals.length===state.selectedIndicators.length&&vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:null}
function featureValue(feature,scale=state.scale,year=state.year){if(!state.selectedIndicators.length||!feature)return null;if(scale==='barrio')return barrioValue(feature.properties.BARRIO,year);if(scale==='manzana')return null;const barrios=state.layers.barrio.features.filter(b=>scale==='comuna'||norm(b.properties.TERRITORIO||territorioBarrio(b.properties.BARRIO))===norm(feature.properties.TERRITORIO));const vals=barrios.map(b=>barrioValue(b.properties.BARRIO,year)).filter(Number.isFinite);return vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:null}
const currentFeatures=()=>state.layers[state.scale]?.features??[];
const computedFeatures=(year=state.year)=>currentFeatures().map(f=>{const value=featureValue(f,state.scale,year);return {...f,properties:{...f.properties,GI_VAL:value,GI_RANGO:rangeFor(value)?.name??'Sin datos'}}});
const selectedComputed=()=>{if(!state.selectedFeature)return null;const key=levelFields[state.scale];return computedFeatures().find(f=>norm(f.properties[key])===norm(state.selectedFeature.properties[key]))};
function renderIndicators(){const options=codesAvailable();state.selectedIndicators=state.selectedIndicators.filter(c=>options.some(i=>i.codigo===c));if(!state.selectedIndicators.length&&options.length)state.selectedIndicators=[options[0].codigo];$('indicatorList').innerHTML=options.map(i=>`<label class="indicator-option"><input type="checkbox" value="${esc(i.codigo)}" ${state.selectedIndicators.includes(i.codigo)?'checked':''}><span><b>${esc(i.codigo)}</b> · ${esc(i.indicador)}<small>${esc(i.unidad??'Unidad no especificada')}</small></span></label>`).join('')||'<p class="note">Seleccione al menos una dimensión con indicadores disponibles.</p>';$('indicatorList').querySelectorAll('input').forEach(input=>input.addEventListener('change',()=>{state.selectedIndicators=[...$('indicatorList').querySelectorAll('input:checked')].map(x=>x.value);refresh()}));renderFormula()}
function selectedNames(){return state.selectedIndicators.map(indicatorByCode).filter(Boolean).map(i=>`${i.codigo} · ${i.indicador}`)}
function renderFormula(){const n=state.selectedIndicators.length;$('groupFormula').textContent=n>1?`Promedio simple de ${n} resultados normalizados: ${selectedNames().join('; ')}.`:n===1?`${selectedNames()[0]}. Resultado individual normalizado.`:'Seleccione uno o varios indicadores.';$('valueLabel').textContent=n>1?'Promedio agrupado':'Valor normalizado';$('indicatorCodes').innerHTML=state.selectedIndicators.map(c=>`<b>${esc(c)}</b>`).join('')}
function renderLegend(){$('legendItems').innerHTML=palette.map(p=>`<div class="legend-row"><i class="swatch" style="background:${p.color}"></i><span>${p.name}</span><b>${p.label}</b></div>`).join('')}
function refreshMap(){const fc={type:'FeatureCollection',features:computedFeatures()};if(!map){$('mapStatus').textContent=`${fc.features.length.toLocaleString('es-CL')} unidades cargadas · mapa no disponible`;return}if(map.getSource('territorial'))map.getSource('territorial').setData(fc);$('mapStatus').textContent=`${fc.features.length.toLocaleString('es-CL')} unidades ${state.scale} · resultados ${state.year}`}
function metrics(feature,year=state.year){const features=computedFeatures(year),values=features.map(f=>f.properties.GI_VAL).filter(Number.isFinite),value=feature?featureValue(feature,state.scale,year):null,avg=values.length?values.reduce((a,b)=>a+b,0)/values.length:null,sorted=[...values].sort((a,b)=>b-a);return {features,values,value,avg,rank:Number.isFinite(value)?sorted.findIndex(v=>v===value)+1:null}}
function analysisFor(feature){if(!feature)return 'Seleccione una unidad territorial para generar el análisis.';const name=feature.properties[levelFields[state.scale]],m=metrics(feature),range=rangeFor(m.value);if(!Number.isFinite(m.value))return `${name} no dispone de un resultado completo para la selección actual.`;const relation=Math.abs(m.value-m.avg)<.005?'prácticamente igual al':m.value>m.avg?'sobre el':'bajo el';let text=`${state.scale==='barrio'?'El barrio ':state.scale==='territorio'?'El territorio ':'La comuna '}${name} obtiene un resultado normalizado de ${fmt(m.value)}, correspondiente al rango ${range.name} según los rangos de valoración utilizados en el PLADECO Santiago 2024–2034. El resultado está ${relation} promedio general de ${state.scale==='barrio'?'los barrios':state.scale==='territorio'?'los territorios':'la comuna'} con datos (${fmt(m.avg)}) y ocupa la posición ${m.rank} de ${m.values.length}.`;if(state.compareYear){const old=featureValue(feature,state.scale,state.compareYear);text+=Number.isFinite(old)?` Frente a ${state.compareYear}, la variación es ${m.value-old>=0?'+':''}${fmt(m.value-old)} puntos normalizados.`:` No existe un resultado completo para compararlo con ${state.compareYear}.`}if(state.scale!=='barrio')text+=' Este valor corresponde al promedio de resultados normalizados de los barrios que integran la unidad, no a un recálculo del indicador original.';if(state.selectedIndicators.some(c=>inverseCodes.has(c)))text+=' La interpretación considera variables con normalización inversa, ya transformadas para que un mayor resultado normalizado exprese una condición más favorable.';return text}
function renderCards(){const selected=selectedComputed(),m=metrics(selected),name=selected?.properties[levelFields[state.scale]]??'Haz clic en una unidad del mapa',unitPlural={barrio:'barrios',territorio:'territorios',comuna:'comuna'}[state.scale]||'unidades';$('selectedValue').textContent=fmt(m.value);$('selectedName').textContent=name;$('averageLabel').textContent=state.scale==='comuna'?'Resultado comunal':`Promedio de ${unitPlural} con datos`;$('scaleAverage').textContent=fmt(m.avg);$('validCount').textContent=state.scale==='comuna'?'Promedio de barrios con resultados':`${m.values.length} de ${m.features.length} ${unitPlural} · incluye la unidad seleccionada`;$('rankValue').textContent=m.rank?`${m.rank}°`:'–';$('rankDetail').textContent=m.rank?`de ${m.values.length} ${unitPlural} con datos`:`Selecciona un ${state.scale} en el mapa`;$('rangeValue').textContent=rangeFor(m.value)?.name??'Sin datos';const v25=selected?featureValue(selected,state.scale,2025):null,v26=selected?featureValue(selected,state.scale,2026):null;$('changeValue').textContent=!state.compareYear?'Comparación desactivada':Number.isFinite(v25)&&Number.isFinite(v26)?`Cambio 2025→2026: ${v26-v25>=0?'+':''}${fmt(v26-v25)}`:'Comparación no disponible';$('contextUnit').textContent=selected?name:'Seleccione una unidad';renderHierarchy(selected)}
function aggregateFor(level,name,year){if(level==='barrio'){const f=state.layers.barrio.features.find(x=>norm(x.properties.BARRIO)===norm(name));return f?featureValue(f,'barrio',year):null}if(level==='territorio'){const f=state.layers.territorio.features.find(x=>norm(x.properties.TERRITORIO)===norm(name));return f?featureValue(f,'territorio',year):null}return featureValue(state.layers.comuna.features[0],'comuna',year)}
function renderHierarchy(feature){if(!feature){$('hierarchyValues').innerHTML='<span class="note">Haz clic en el mapa para ver barrio, territorio y comuna.</span>';return}const p=feature.properties,items=[],territorio=territorioDePropiedades(p);if(state.scale==='barrio')items.push(['Barrio',p.BARRIO,aggregateFor('barrio',p.BARRIO,state.year)]);if(state.scale!=='comuna')items.push(['Territorio',territorio,aggregateFor('territorio',territorio,state.year)]);items.push(['Comuna','SANTIAGO',aggregateFor('comuna','SANTIAGO',state.year)]);$('hierarchyValues').innerHTML=items.map(([level,name,value])=>`<div class="context-pill"><span>${level}</span><strong>${esc(name)}</strong><b>${fmt(value)}</b></div>`).join('')}
function selectedTerritorialNames(){if(!state.selectedFeature)return[];const p=state.selectedFeature.properties;if(state.scale==='barrio')return[p.BARRIO];if(state.scale==='territorio')return state.layers.barrio.features.filter(b=>norm(b.properties.TERRITORIO||territorioBarrio(b.properties.BARRIO))===norm(p.TERRITORIO||territorioBarrio(p.BARRIO))).map(b=>b.properties.BARRIO);return[]}
function projectsFor(code){const unitNames=selectedTerritorialNames().map(norm),aliases=new Map([['DIEZDEJULIO','10DEJULIO']]);const targetNames=new Set(unitNames.flatMap(n=>[n,aliases.get(n)].filter(Boolean)));return state.initiatives.filter(i=>i.indicador===code).map(i=>{const place=norm(i.barrio),exact=targetNames.has(place),general=place===norm('DIVERSOS SECTORES'),communal=norm(i.alcance)===norm('COMUNAL');return{...i,score:exact?100:general?70:communal?60:10}}).sort((a,b)=>b.score-a.score||a.iniciativa.localeCompare(b.iniciativa,'es'))}
function renderPolicyLinks(){if(!$("policyLinks"))return;const selected=state.selectedIndicators.map(code=>({code,indicator:indicatorByCode(code),link:strategicLinks[code]})).filter(x=>x.indicator&&x.link);if(!selected.length){$('policyLinks').innerHTML='<p class="note">No existe una vinculación definida para la selección actual.</p>';return}$('policyLinks').innerHTML=selected.map(({code,indicator,link})=>{const projects=projectsFor(code);const components=[...new Set(projects.map(p=>p.tipologia).filter(Boolean))];return`<article class="policy-card"><div class="policy-code">${esc(indicator.codigo)} · ${esc(indicator.indicador)}</div><dl><dt>Dimensión</dt><dd>${esc(link.dimension)}</dd><dt>Eje</dt><dd>${esc(link.eje)}</dd><dt>Componente</dt><dd>${esc(components.join(' · ')||link.componentes[0])}</dd></dl><div class="linked-project"><span>Proyectos asociados que pueden contribuir a mejorar el indicador</span><div class="linked-projects">${projects.length?projects.map(p=>`<div class="linked-project-item"><strong>${esc(p.iniciativa)}</strong><small>${esc(p.alcance)} · ${esc(p.barrio)} · ${esc(p.plazo)}</small></div>`).join(''):'<strong>Sin proyecto asociado en la cartera vigente</strong>'}</div></div></article>`}).join('')+'<p class="policy-note">Fuente de validación: cartera PDT–PLADECO de 307 iniciativas. El visor publica únicamente los proyectos asociados a cada indicador. “Componente” corresponde a la tipología de la iniciativa. La asociación es técnica y orientativa; la mejora debe comprobarse después de ejecutar y evaluar los proyectos.</p>'}
function renderChart(){const title={ranking:'Ranking territorial',ranges:'Distribución por rangos PLADECO',trend:'Evolución y análisis temporal'}[state.view];$('chartTitle').textContent=title;({ranking:renderRanking,ranges:renderRanges,trend:renderTrend}[state.view])()}
function renderRanking(){const rows=computedFeatures().filter(f=>Number.isFinite(f.properties.GI_VAL)).sort((a,b)=>b.properties.GI_VAL-a.properties.GI_VAL);$('chart').innerHTML=rows.map((f,i)=>`<div class="bar-row"><span>${i+1}. ${esc(f.properties[levelFields[state.scale]])}</span><b>${fmt(f.properties.GI_VAL)}</b><div class="bar-track"><div class="bar-fill" style="width:${f.properties.GI_VAL*100}%"></div></div></div>`).join('')||'<p class="note">No existen resultados para esta escala.</p>'}
function renderRanges(){const vals=computedFeatures().map(f=>f.properties.GI_VAL).filter(Number.isFinite),counts=palette.map(p=>vals.filter(v=>rangeFor(v)?.name===p.name).length),total=vals.length,units={barrio:'barrios',territorio:'territorios',comuna:'comunas'}[state.scale]||'unidades',top=Math.max(...counts),dominant=palette[counts.indexOf(top)],selected=selectedComputed(),selectedName=selected?.properties[levelFields[state.scale]],selectedValue=selected?.properties.GI_VAL,selectedRange=rangeFor(selectedValue),selectionText=selected&&Number.isFinite(selectedValue)?`${state.scale==='barrio'?'El barrio ':state.scale==='territorio'?'El territorio ':'La comuna '}${selectedName} obtiene ${fmt(selectedValue)} y se ubica en el rango ${selectedRange.name}. `:'Seleccione una unidad en el mapa para identificar su rango. ';$('chart').innerHTML=total?`<div class="range-stack">${palette.map((p,i)=>`<div class="range-segment" title="${p.name}: ${counts[i]}" style="width:${counts[i]/total*100}%;background:${p.color}">${counts[i]||''}</div>`).join('')}</div><div class="range-columns"><span>Rango PLADECO</span><b>Cantidad de ${units} · porcentaje</b></div><div class="range-detail">${palette.map((p,i)=>`<div class="legend-row"><i class="swatch" style="background:${p.color}"></i><span>${p.name} · ${p.label}</span><b>${counts[i]} · ${fmt(counts[i]/total*100)}%</b></div>`).join('')}</div><p class="analysis range-summary">${selectionText}De ${total} ${units} con datos, ${top} (${fmt(top/total*100)}%) se ubican en el rango ${dominant.name}, que es el grupo más numeroso. La columna derecha muestra cantidad y porcentaje.</p>`:'<p class="note">No existen resultados para distribuir.</p>'}
function renderTrend(){const f=state.selectedFeature;if(!f){$('chart').innerHTML='<p class="note">Haz clic en una unidad del mapa para ver su evolución.</p>';return}const name=esc(f.properties[levelFields[state.scale]]),years=state.compareYear?[2025,2026]:[state.year],vals=years.map(y=>featureValue(f,state.scale,y));if(vals.some(v=>!Number.isFinite(v))){$('chart').innerHTML='<p class="note">No existen resultados completos para el análisis temporal solicitado.</p>';return}if(years.length===1){$('chart').innerHTML=`<div class="single-year"><strong>${name} · ${state.year}</strong><span>${fmt(vals[0])}</span><b>${rangeFor(vals[0]).name}</b></div><p class="analysis">${esc(analysisFor(f))}</p>`;return}const change=vals[1]-vals[0],direction=Math.abs(change)<.005?'estable':change>0?'positiva y creciente':'negativa y decreciente',indicatorNames=selectedNames().join(' e '),unit=f.properties[levelFields[state.scale]],temporal=`Para el análisis de ${indicatorNames}, ${state.scale==='barrio'?'el barrio ':''}${unit} pasa de ${fmt(vals[0])} en ${years[0]} a ${fmt(vals[1])} en ${years[1]}; por lo tanto, presenta una evolución ${direction} de ${Math.abs(change).toLocaleString('es-CL',{minimumFractionDigits:2,maximumFractionDigits:2})} puntos normalizados. ${Math.abs(change)<.005?'El resultado no presenta un cambio relevante.':change>0?'Este cambio es favorable porque un valor normalizado mayor representa una mejor condición.':'Este cambio es desfavorable porque disminuye el resultado normalizado.'} ${state.selectedIndicators.some(c=>inverseCodes.has(c))?'Las variables con normalización inversa ya fueron transformadas para que un valor mayor represente una condición más favorable.':''}`;const y=v=>190-v*145;$('chart').innerHTML=`<svg class="trend-svg" viewBox="0 0 300 215"><line x1="45" y1="190" x2="270" y2="190" stroke="#36506a"/><line x1="85" y1="${y(vals[0])}" x2="230" y2="${y(vals[1])}" stroke="#20c6c7" stroke-width="4"/><circle cx="85" cy="${y(vals[0])}" r="7" fill="#337ce5"/><circle cx="230" cy="${y(vals[1])}" r="7" fill="#20c6c7"/><text x="68" y="207" class="trend-label">${years[0]}</text><text x="213" y="207" class="trend-label">${years[1]}</text><text x="66" y="${y(vals[0])-12}" class="trend-label">${fmt(vals[0])}</text><text x="211" y="${y(vals[1])-12}" class="trend-label">${fmt(vals[1])}</text></svg><p class="analysis">${esc(temporal)}</p>`}
function reportActions(){return '<p class="report-scope">Los textos describen resultados normalizados y no establecen causalidad.</p>'}
function openMethod(){const selected=state.selectedIndicators.map(indicatorByCode).filter(Boolean),f=state.selectedFeature;$('dialogContent').innerHTML=`<h2>Ficha de indicador${selected.length===1?'':'es'}</h2><p class="note">Resultados publicados exclusivamente desde 2025 y 2026 de Síntesis 2.</p>${selected.map(i=>`<section class="indicator-sheet"><h3>${esc(i.codigo)} · ${esc(i.indicador)}</h3><p>${esc(indicatorDescription(i))}</p><dl class="dialog-grid"><dt>Unidad de referencia</dt><dd>${esc(i.unidad??'–')}</dd><dt>Sentido</dt><dd>${esc(directionText(i))}</dd><dt>Disponibilidad</dt><dd>2025: ${i.publicado_2025?'sí':'no'} · 2026: ${i.publicado_2026?'sí':'no'}</dd></dl></section>`).join('')}${selected.length>1?`<h3>Resultado agrupado</h3><p>Promedio simple de ${selected.length} resultados normalizados: ${esc(selectedNames().join('; '))}. Si falta un componente, la unidad queda sin resultado.</p>`:''}<h3>Análisis de la selección territorial</h3><p>${esc(analysisFor(f))}</p>${reportActions()}`;$('infoDialog').showModal()}
function openReport(){const f=state.selectedFeature,name=f?.properties[levelFields[state.scale]]??'Sin unidad seleccionada',value=f?featureValue(f):null,old=f&&state.compareYear?featureValue(f,state.scale,state.compareYear):null,descriptions=state.selectedIndicators.map(indicatorByCode).filter(Boolean);$('dialogContent').innerHTML=`<h2>Reporte ${state.compareYear?'comparativo':'de resultados'}</h2><p><b>${esc(name)}</b> · ${esc(state.scale)} · ${state.year}${state.compareYear?` frente a ${state.compareYear}`:''}</p><table class="report-table"><tr><th>Indicadores seleccionados</th><td>${esc(selectedNames().join('; ')||'Sin selección')}</td></tr><tr><th>Descripción breve</th><td>${descriptions.map(i=>esc(indicatorDescription(i))).join('<br>')}</td></tr><tr><th>Resultado ${state.year}</th><td>${fmt(value)}</td></tr>${state.compareYear?`<tr><th>Resultado ${state.compareYear}</th><td>${fmt(old)}</td></tr><tr><th>Variación</th><td>${Number.isFinite(value)&&Number.isFinite(old)?`${value-old>=0?'+':''}${fmt(value-old)}`:'No comparable'}</td></tr>`:''}<tr><th>Rango PLADECO</th><td>${rangeFor(value)?.name??'Sin datos'}</td></tr><tr><th>Agregación</th><td>${state.selectedIndicators.length>1?'Promedio simple de resultados normalizados':'Indicador individual'}${state.scale!=='barrio'?'; promedio territorial de barrios':''}</td></tr></table><h3>Análisis de resultados</h3><p>${esc(analysisFor(f))}</p><p class="note">Fuente pública: resultados normalizados 2025–2026 de Síntesis 2. No se publican fórmulas, cálculos internos ni capas específicas de indicadores.</p>${reportActions()}`;$('infoDialog').showModal()}
function downloadPdf(){const text=$('dialogContent').innerText;if(window.jspdf?.jsPDF){const doc=new window.jspdf.jsPDF({unit:'mm',format:'a4'}),lines=doc.splitTextToSize(text,180);let y=15;lines.forEach(line=>{if(y>282){doc.addPage();y=15}doc.text(line,15,y);y+=5});doc.save(`geoindicadores-${state.scale}-${state.year}.pdf`)}else window.print()}
function syncCompareYears(){const other=state.year===2025?2026:2025;$('compareYearSelect').innerHTML=`<option value="none">Ninguno</option><option value="${other}">${other}</option>`;state.compareYear=null;$('compareYearSelect').value='none'}
function bind(){$('scaleSelect').addEventListener('change',e=>{state.scale=e.target.value;state.selectedFeature=null;refresh()});$('yearSelect').addEventListener('change',e=>{state.year=Number(e.target.value);syncCompareYears();renderIndicators();refresh()});$('compareYearSelect').addEventListener('change',e=>{state.compareYear=e.target.value==='none'?null:Number(e.target.value);renderIndicators();refresh()});$('dimensionList').querySelectorAll('input').forEach(x=>x.addEventListener('change',()=>{state.selectedDimensions=[...$('dimensionList').querySelectorAll('input:checked')].map(i=>i.value);renderIndicators();refresh()}));$('clearIndicators').addEventListener('click',()=>{state.selectedIndicators=[];renderIndicators();refresh()});document.querySelectorAll('.tabs button').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.view=b.dataset.view;renderChart()}));$('methodButton').addEventListener('click',openMethod);$('reportButton').addEventListener('click',openReport);document.querySelector('.close-dialog').addEventListener('click',()=>$('infoDialog').close());$('printDialog').addEventListener('click',()=>window.print());$('pdfDialog').addEventListener('click',downloadPdf)}
function refresh(){renderFormula();refreshMap();renderCards();renderChart();renderPolicyLinks()}
async function init(){renderLegend();bind();[state.db,state.initiatives]=await Promise.all([fetch('./data/sintesis-visor.json').then(r=>r.json()),fetch('./data/proyectos-asociados-indicadores.json').then(r=>r.ok?r.json():[]).catch(()=>[])]);for(const [level,files] of Object.entries(layerFiles)){const parts=await Promise.all(files.map(f=>fetch(`./data/${f}?v=0.9.11`).then(r=>r.json())));state.layers[level]={type:'FeatureCollection',features:parts.flatMap(p=>p.features)}}$('sourceStatus').textContent='Resultados normalizados: Síntesis 2 · 2025 y 2026';renderIndicators();try{map=new maplibregl.Map({container:'map',style:{version:8,sources:{osm:{type:'raster',tiles:['https://tile.openstreetmap.org/{z}/{x}/{y}.png'],tileSize:256,attribution:'© OpenStreetMap'}},layers:[{id:'osm',type:'raster',source:'osm',paint:{'raster-saturation':-.75,'raster-brightness-max':.55}}]},center:[-70.653,-33.451],zoom:12.5});map.addControl(new maplibregl.NavigationControl(),'top-right');map.on('load',()=>{map.addSource('territorial',{type:'geojson',data:{type:'FeatureCollection',features:[]}});map.addLayer({id:'territorial-fill',type:'fill',source:'territorial',paint:{'fill-color':['match',['get','GI_RANGO'],'Muy bajo',palette[0].color,'Bajo',palette[1].color,'Medio',palette[2].color,'Alto',palette[3].color,'#607486'],'fill-opacity':.72}});map.addLayer({id:'territorial-line',type:'line',source:'territorial',paint:{'line-color':'#e8f7ff','line-width':1}});map.on('click','territorial-fill',e=>{state.selectedFeature=e.features[0];renderCards();renderChart();renderPolicyLinks();const p=e.features[0].properties,name=p[levelFields[state.scale]],v=featureValue(state.selectedFeature),inds=selectedNames();new maplibregl.Popup({maxWidth:'360px'}).setLngLat(e.lngLat).setHTML(`<strong>${esc(name)}</strong><br>${esc(state.scale)} · ${state.year}<br><b>Indicador${inds.length===1?'':'es'}:</b> ${esc(inds.join('; '))}<br>${inds.length>1?`<b>Promedio de ${inds.length} resultados normalizados</b><br>`:''}Resultado: ${fmt(v)} · ${rangeFor(v)?.name??'Sin datos'}`).addTo(map)});map.on('mouseenter','territorial-fill',()=>map.getCanvas().style.cursor='pointer');map.on('mouseleave','territorial-fill',()=>map.getCanvas().style.cursor='');refresh()})}catch(error){console.error(error);map=null;$('mapStatus').textContent='Mapa no disponible en este navegador';renderCards();renderChart();renderPolicyLinks()}}
init().catch(error=>{console.error(error);$('sourceStatus').textContent='Error al cargar la base';$('mapStatus').textContent='No fue posible iniciar el visor'});